image:
  - Visual Studio 2017
  - Ubuntu

stack: jdk 8
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  CLIENTTESTS_XRAY_URL:
    secure: RIh0gGFDn2JAnLUEEqLsQj2LHpPj3KIjKiRyPeN4nT8Yxi5imzLTTJAGZaCz/DpM
  CLIENTTESTS_XRAY_USERNAME:
    secure: YEB5Wiv9a2vNpUhy+MfL+A==
  CLIENTTESTS_XRAY_PASSWORD:
    secure: Um8o75MQIieSavIemF4ySA==

test_script:
  - sh: ./gradlew test
  - cmd: gradlew.bat test

# Don't actually build.
build: off