updateCommitStatus: &UPDATE_COMMIT_STATUS update_commit_status xrayJavaSnapshotGit --context "$step_name"

pipelines:
  - name: build_xray_java_snapshot
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: java
            versions:
              - "8.0.0"

    steps:
      - name: Snapshot
        type: Bash
        configuration:
          inputResources:
            - name: xrayJavaSnapshotGit
          integrations:
            - name: ojo
        execution:
          onStart:
            - *UPDATE_COMMIT_STATUS
            - restore_cache_files gradle_cache $res_xrayJavaSnapshotGit_resourcePath/.gradle
          onExecute:
            - cd $res_xrayJavaSnapshotGit_resourcePath

            # Set env
            - export CI=true
            - export JFROG_CLI_BUILD_NAME=xray-client-java
            - export JFROG_CLI_BUILD_NUMBER=$run_number

            # Download JFrog CLI
            - curl -fL https://getcli.jfrog.io | sh && chmod +x jfrog

            # Configure JFrog CLI
            - ./jfrog c add ojo --artifactory-url $int_ojo_rt_url --access-token=$int_ojo_rt_token
            - ./jfrog rt gradlec --use-wrapper --deploy-ivy-desc=false --deploy-maven-desc=true
              --server-id-resolve ojo --repo-resolve remote-repos
              --server-id-deploy ojo --repo-deploy oss-snapshot-local

            # Run test, build and publish snapshot
            - >
              env -i PATH=$PATH HOME=$HOME GRADLE_OPTS=-Dorg.gradle.daemon=false
              JFROG_CLI_BUILD_NAME=$JFROG_CLI_BUILD_NAME
              JFROG_CLI_BUILD_NUMBER=$JFROG_CLI_BUILD_NUMBER
              ./jfrog rt gradle clean install artifactoryPublish -x test
            - ./jfrog rt bp

          onComplete:
            # Show tests in the *Tests* tab
            - save_tests $res_xrayJavaSnapshotGit_resourcePath/build/test-results/test/

            - *UPDATE_COMMIT_STATUS

            # Save .m2 cache
            - add_cache_files $res_xrayJavaSnapshotGit_resourcePath/.gradle gradle_cache